site_name: BitMakeLab
site_url: https://thinkcreatelearn.co.uk/bitmake
theme:
  name: material
  features:
    - navigation.tabs  # Enables the tabbed navigation style for the site
  palette:
    primary: custom # Sets the primary color of the site to a custom color defined in the extra.css file
    accent: custom # Sets the accent color of the site to a custom color defined in the extra.css file
  logo: assets/logo.png

# Site navigation structure
nav:
  - Home: index.md
  - Projects: 
    - Overview: projects/overview.md
    - Wheeled Robots:
      - Overview: projects/wheeled-robots/overview.md
      - Project 1.01 - Build a Basic Robot: projects/wheeled-robots/project1.01/index.md
      - Project 1.02 - Add Lights to your Robot: projects/wheeled-robots/project1.02/index.md
  - Reference: 
    - Overview: reference/overview.md
    - Inputs:
      - Button: reference/inputs/button/index.md
      - Potentiometer: reference/inputs/potentiometer/index.md
      - colour sensor: reference/inputs/colour senor/ondex.md
    - Outputs:
      - LED: reference/outputs/led/index.md
    - Motors:
      - DC Motor: reference/motors/dc-motor/index.md
      - Servo Motor: reference/motors/servo-motor/index.md
    - Working with Data:
      - Serial output: reference/working-with-data/serial-output/index.md
      - Data logging: reference/working-with-data/data-logging/index.md
  - Make the kit:
      - Overview: make-the-kit/overview.md
  - Blog:
    - blog/index.md
  - About: about.md  

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - attr_list # add attributes to some markdown elements such as images using curly braces
  - md_in_html # allows markdown to be used inside HTML blocks

  # Python markdown extensions for extra functionality
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  # Social links
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=social#social-links
  social:
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/tcreatelearn/

    - icon: fontawesome/brands/github
      link: https://github.com/lewfer

  generator: false # Hides the "Generated by MkDocs" message in the footer of the site

  # Custom variables for use in the macros plugin
  bmlgithubpages: https://lewfer.github.io/BitMakeLab
  bmlgithub: https://github.com/lewfer/BitMakeLab/tree/main/

plugins:
  - blog # enables the blog functionality for the site https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
  - search # enables the search box in the top right of the site
  - macros # gives us the ability to use variables and macrosin our markdown files https://mkdocs-macros-plugin.readthedocs.io

copyright: Copyright &copy; 2026 - Think Create Learn Ltd. Licensed under the Creative Commons BY-SA-NC-SA licence.